# Site settings
title: Learning Quantum Computing
description: A new era of Computing Machines arriving!!!
keywords: Quantum, Computing, IT, Technology, Science, Engineering, Programming, Tutorials, Blog, Posts
author: Rúben André Barreiro
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
